### ISSUE TITLE
error for basic test

### ISSUE THREAD

**Issue by pbpf** [bodono/scs-python#35]
I install scs in python3.8.4 and windows10 success, however when I try
> python test/solve_random_cone_prob.py
I got this 
```
Traceback (most recent call last):
  File "test/solve_random_cone_prob.py", line 2, in <module>
    import scs
  File "D:\Programs\Python38\lib\site-packages\scs-2.1.3-py3.8-win-amd64.egg\scs\__init__.py", line 5, in <module>
    import _scs_direct
ImportError: DLL load failed while importing _scs_direct: 找不到指定的模块（The specified module was not found）。
```

**Comment by bodono** [comment]
This works locally for me on mac and linux, I don't have a windows machine to test with unfortunately. It looks to me like something is broken with your PATH variables, since scs is installed but it can't find the dll. I would manually find the installed dll and make sure the PATH variable(s) are pointing to the right place.
