### ISSUE TITLE
Duplicate openblas library

### ISSUE THREAD

**Issue by rjungbeck** [bodono/scs-python#64]
scs-python requires NumPy. NumPy already includes openblas. So distributing a private copy with scs-python increases distribution size for applications that contain complete environments (so that they can be used without a Python installation), It also increases RAM requirements as both copies get loaded into RAM.

NB: 89/ 91.46 of the wheel / disk size of scs-python is linopenblas.

**Comment by syockit** [comment]
To be fair, SciPy also does the same thing.

**Comment by enzbus** [comment]
I know this is old, but we recently re-wrote the packaging code (now we use `meson`) and sadly have the same situation (on Linux and Windows, for Mac we link against the system libraries). You can always compile from source instead, by doing `pip install scs  --no-binary`. On Linux this works well, as long as you have some `blas` in your system (openblas and netlib both work). On Windows it's trickier and we recommend using our compiled wheels instead.  We discussed with Numpy packaging maintainers and we may in the future be able to link against their shipped blas but it's not guaranteed (the problem is mostly windows, which lacks relative path support for dynamic libraries). Our current solution is optimized to work out-of-the-box for regular users who pip install cvxpy, if you want more granular control you may prefer to compile `scs` directly.
